@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYW5naWVjYWJhbDM1QGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2MzUwMjU3NywiZXhwIjoxNzYzNTg4OTc3fQ.BSFZatAIgrSlp76Vcyn9Tn0TYY3PH3YHSD0O3_sX0y4
### Crear factura
POST {{baseUrl}}/invoices
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": 1,
    "orderId": 3,
    "paymentId": 3,
    "totalAmount": 450000,
    "invoiceNumber": "INV-2025-001"
}

### Obtener todas las facturas
GET {{baseUrl}}/invoices
Authorization: Bearer {{token}}

### Obtener factura por ID
GET {{baseUrl}}/invoices/1
Authorization: Bearer {{token}}

### Actualizar factura
PATCH {{baseUrl}}/invoices/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "totalAmount": 260.00
}

### Cancelar factura
PATCH {{baseUrl}}/invoices/1/cancel
Authorization: Bearer {{token}}

### Eliminar factura
DELETE {{baseUrl}}/invoices/1
Authorization: Bearer {{token}}
