@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiYW5naWVjYWJhbDM1QGdtYWlsLmNvbSIsInJvbGUiOiJDTElFTlQiLCJpYXQiOjE3NjM2MTMwMzksImV4cCI6MTc2MzY5OTQzOX0.RPNDO9GuLBwZ_82DY91gn4H6liluLRKBxmACepy1ppU
@sessionId = cs_test_a1jDqSMcyUdyJD0X8j2nQetyaaEDqqCZZI9dpAjrbaswKBhgshfnNwjGbl
### Crear sesión de pago
POST {{baseUrl}}/payments/stripe/checkout
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "orderId":5
}

### Verificar Estado de Pago
GET {{baseUrl}}/payments/verify?sessionId={{sessionId}}
Authorization: Bearer {{token}}

### Obtener todos los pagos (solo admin)
GET {{baseUrl}}/payments
Authorization: Bearer {{token}}

### Obtener pago por ID
GET {{baseUrl}}/payments/3
Authorization: Bearer {{token}}

### Actualizar un pago
PATCH {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "method": "paypal",
    "status": "paid"
}

### Cambiar estado del pago
PATCH {{baseUrl}}/payments/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "refunded"
}

### Eliminar pago
DELETE {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
