@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYW5naWVjYWJhbDM1QGdtYWlsLmNvbSIsInJvbGUiOiJDTElFTlQiLCJpYXQiOjE3NjM1MDIxNDYsImV4cCI6MTc2MzU4ODU0Nn0.FABTtTrddm7Ig5TmczUCJioXkNCRHv1YFpR1zyxVYe4

### Crear usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "nombre": "Mateo",
    "apellido": "Aponte",
    "email": "apontemurciamateo@gmail.com",
    "telefono": "32000000",
    "password": "12345678"
}

### Recuperar Contraseña



### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "angiecabal35@gmail.com",
    "password": "12345678"
}

### Listar todos los usuarios (solo admin)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Obtener un usuario por ID
GET {{baseUrl}}/users/1
Authorization: Bearer {{token}}

### Actualizar un usuario
PATCH {{baseUrl}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefono": "31099879",
    "password": "sissonidoClaveSegura"
}

### Eliminar un usuario (solo admin)
DELETE {{baseUrl}}/users/9
Authorization: Bearer {{token}}
