@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImFuZ2llY2FiYWwzNUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNTQ0MjEsImV4cCI6MTc2MzI0MDgyMX0.1eIMvB4rcehlncHCOD4VSs9refki9lashXCpaZ0-naY

### Crear usuario
POST {{baseUrl}}/users
Content-Type: application/json

{
    "nombre": "Adriana",
    "apellido": "Caicedo",
    "email": "angiecabal35@gmail.com",
    "telefono": "3200000002",
    "password": "12345678",
    "role": "ADMIN"
}

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "angiecabal35@gmail.com",
    "password": "12345678"
}

### Listar todos los usuarios (solo admin)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Obtener un usuario por ID
GET {{baseUrl}}/users/1
Authorization: Bearer {{token}}

### Actualizar un usuario
PATCH {{baseUrl}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefono": "31099879",
    "password": "sissonidoClaveSegura"
}

### Eliminar un usuario (solo admin)
DELETE {{baseUrl}}/users/9
Authorization: Bearer {{token}}
