@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImFuZ2llY2FiYWwzNUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNTczNzMsImV4cCI6MTc2MzI0Mzc3M30.BzI7NpiIzdAUcGFSOMWOl9OqpcJumK0DjsVpzy98Hwg

### Crear un carrito para un usuario
POST {{baseUrl}}/carts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": 1,
    "productIds": [2]
}

### Obtener todos los carritos (solo admin)
GET {{baseUrl}}/carts
Authorization: Bearer {{token}}

### Obtener un carrito por ID
GET {{baseUrl}}/carts/1
Authorization: Bearer {{token}}

### Actualizar productos del carrito
PATCH {{baseUrl}}/carts/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productIds": [3]
}

### Confirmar compra (checkout)
PATCH {{baseUrl}}/carts/1/checkout
Authorization: Bearer {{token}}

### Eliminar carrito
DELETE {{baseUrl}}/carts/1
Authorization: Bearer {{token}}
