@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6ImFuZ2llY2FiYWwzNUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNTQ0MjEsImV4cCI6MTc2MzI0MDgyMX0.1eIMvB4rcehlncHCOD4VSs9refki9lashXCpaZ0-naY
POST {{baseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Telefonia",
    "description": "eléfonos móviles, accesorios (cargadores, fundas), dispositivos de comunicación."
}

### Crear otra categoría
POST {{baseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Oficina",
    "description": "Artículos de papelería y suministros de oficina"
}

### Listar categorías
GET {{baseUrl}}/categories
Authorization: Bearer {{token}}

### Obtener categoría por ID
GET {{baseUrl}}/categories/2
Authorization: Bearer {{token}}

### Actualizar categoría
PATCH {{baseUrl}}/categories/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Equipos electrónicos y de cómputo"
}

### Eliminar categoría
DELETE {{baseUrl}}/categories/1
Authorization: Bearer {{token}}
